-- Migration Oracle para dominio Lara (Agente de Cobranca)
-- Execucao segura/idempotente: ignora objetos ja existentes.

SET DEFINE OFF;

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_CLIENTES_CACHE (
      ID VARCHAR2(64) PRIMARY KEY,
      CODCLI NUMBER(12) NOT NULL,
      CLIENTE VARCHAR2(255) NOT NULL,
      CPF_CNPJ_MASK VARCHAR2(30),
      TELEFONE VARCHAR2(40),
      WA_ID VARCHAR2(40),
      FILIAL VARCHAR2(40),
      STATUS_RELACIONAMENTO VARCHAR2(60),
      TOTAL_ABERTO NUMBER(14,2) DEFAULT 0 NOT NULL,
      QTD_TITULOS NUMBER(10) DEFAULT 0 NOT NULL,
      RISCO VARCHAR2(20),
      ETAPA_REGUA VARCHAR2(20),
      ULTIMO_CONTATO_EM TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_TITULOS_CACHE (
      ID VARCHAR2(120) PRIMARY KEY,
      CODCLI NUMBER(12) NOT NULL,
      DUPLICATA VARCHAR2(80) NOT NULL,
      PRESTACAO VARCHAR2(20) NOT NULL,
      VALOR NUMBER(14,2) DEFAULT 0 NOT NULL,
      VENCIMENTO DATE,
      DIAS_ATRASO NUMBER(10) DEFAULT 0 NOT NULL,
      CODCOB VARCHAR2(20),
      STATUS_TITULO VARCHAR2(40),
      BOLETO_DISPONIVEL NUMBER(1) DEFAULT 0 NOT NULL,
      PIX_DISPONIVEL NUMBER(1) DEFAULT 0 NOT NULL,
      FILIAL VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_COB_MSG_LOG (
      ID VARCHAR2(64) PRIMARY KEY,
      WA_ID VARCHAR2(40),
      CODCLI NUMBER(12),
      CLIENTE VARCHAR2(255),
      TELEFONE VARCHAR2(40),
      MESSAGE_TEXT VARCHAR2(4000),
      DIRECTION VARCHAR2(20) NOT NULL,
      ORIGEM VARCHAR2(80),
      ETAPA VARCHAR2(20),
      DUPLICS VARCHAR2(500),
      VALOR_TOTAL NUMBER(14,2),
      PAYLOAD_JSON CLOB,
      STATUS VARCHAR2(40),
      SENT_AT TIMESTAMP,
      RECEIVED_AT TIMESTAMP,
      MESSAGE_TYPE VARCHAR2(30),
      OPERATOR_NAME VARCHAR2(120),
      IDEMPOTENCY_KEY VARCHAR2(120),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_CASES (
      ID VARCHAR2(64) PRIMARY KEY,
      WA_ID VARCHAR2(40),
      CODCLI NUMBER(12),
      CLIENTE VARCHAR2(255),
      TIPO_CASE VARCHAR2(80) NOT NULL,
      ETAPA VARCHAR2(20),
      DUPLICATAS VARCHAR2(500),
      VALOR_TOTAL NUMBER(14,2),
      FORMA_PAGAMENTO VARCHAR2(60),
      DETALHE VARCHAR2(4000),
      ORIGEM VARCHAR2(80),
      RESPONSAVEL VARCHAR2(120),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_PROMESSAS_PAGAMENTO (
      ID VARCHAR2(64) PRIMARY KEY,
      WA_ID VARCHAR2(40),
      CODCLI NUMBER(12),
      CLIENTE VARCHAR2(255),
      DUPLICATAS VARCHAR2(500),
      VALOR_TOTAL NUMBER(14,2),
      DATA_PROMETIDA DATE,
      OBSERVACAO VARCHAR2(2000),
      STATUS VARCHAR2(40),
      ORIGEM VARCHAR2(80),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_OPTOUT (
      ID VARCHAR2(64) PRIMARY KEY,
      WA_ID VARCHAR2(40),
      CODCLI NUMBER(12),
      CLIENTE VARCHAR2(255),
      MOTIVO VARCHAR2(300),
      ATIVO NUMBER(1) DEFAULT 1 NOT NULL,
      ORIGEM VARCHAR2(80),
      OBSERVACAO VARCHAR2(2000),
      DATA_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      DATA_ATUALIZACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_REGUA_TEMPLATES (
      ID VARCHAR2(64) PRIMARY KEY,
      ETAPA VARCHAR2(20) NOT NULL,
      NOME_TEMPLATE VARCHAR2(120) NOT NULL,
      CANAL VARCHAR2(40) NOT NULL,
      MENSAGEM_TEMPLATE CLOB NOT NULL,
      ATIVO NUMBER(1) DEFAULT 1 NOT NULL,
      ORDEM_EXECUCAO NUMBER(6) DEFAULT 0 NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_REGUA_EXECUCOES (
      ID VARCHAR2(64) PRIMARY KEY,
      ETAPA VARCHAR2(20) NOT NULL,
      DATA_HORA_EXECUCAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      ELEGIVEL NUMBER(10) DEFAULT 0 NOT NULL,
      DISPARADA NUMBER(10) DEFAULT 0 NOT NULL,
      RESPONDIDA NUMBER(10) DEFAULT 0 NOT NULL,
      CONVERTIDA NUMBER(10) DEFAULT 0 NOT NULL,
      ERRO NUMBER(10) DEFAULT 0 NOT NULL,
      BLOQUEADO_OPTOUT NUMBER(10) DEFAULT 0 NOT NULL,
      VALOR_IMPACTADO NUMBER(14,2) DEFAULT 0 NOT NULL,
      STATUS VARCHAR2(40),
      DETALHES_JSON CLOB,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_INTEGRACOES_LOG (
      ID VARCHAR2(64) PRIMARY KEY,
      INTEGRACAO VARCHAR2(80) NOT NULL,
      TIPO VARCHAR2(80) NOT NULL,
      REQUEST_JSON CLOB,
      RESPONSE_JSON CLOB,
      STATUS_HTTP NUMBER(5),
      STATUS_OPERACAO VARCHAR2(40),
      ERRO_RESUMO VARCHAR2(1000),
      IDEMPOTENCY_KEY VARCHAR2(120),
      CORRELATION_ID VARCHAR2(120),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE LARA_CONFIGURACOES (
      ID VARCHAR2(64) PRIMARY KEY,
      CHAVE VARCHAR2(120) NOT NULL,
      VALOR CLOB,
      DESCRICAO VARCHAR2(400),
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN ex_obj_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_LARA_CLIENTES_CODCLI ON LARA_CLIENTES_CACHE (CODCLI)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_CLIENTES_WA ON LARA_CLIENTES_CACHE (WA_ID)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_CLIENTES_TELEFONE ON LARA_CLIENTES_CACHE (TELEFONE)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_CLIENTES_ATUALIZ ON LARA_CLIENTES_CACHE (UPDATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_TITULOS_CODCLI ON LARA_TITULOS_CACHE (CODCLI, VENCIMENTO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_TITULOS_DUP ON LARA_TITULOS_CACHE (DUPLICATA, PRESTACAO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_TITULOS_VENC ON LARA_TITULOS_CACHE (VENCIMENTO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_MSG_WA ON LARA_COB_MSG_LOG (WA_ID, CREATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_MSG_CODCLI ON LARA_COB_MSG_LOG (CODCLI, CREATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_MSG_SENT ON LARA_COB_MSG_LOG (SENT_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_MSG_IDEMP ON LARA_COB_MSG_LOG (IDEMPOTENCY_KEY)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_CASES_WA ON LARA_CASES (WA_ID, CREATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_CASES_CODCLI ON LARA_CASES (CODCLI, CREATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_PROM_WA ON LARA_PROMESSAS_PAGAMENTO (WA_ID, DATA_PROMETIDA)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_PROM_CODCLI ON LARA_PROMESSAS_PAGAMENTO (CODCLI, DATA_PROMETIDA)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_OPTOUT_WA ON LARA_OPTOUT (WA_ID, ATIVO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_OPTOUT_CODCLI ON LARA_OPTOUT (CODCLI, ATIVO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_LARA_REGUA_TEMPLATE ON LARA_REGUA_TEMPLATES (ETAPA, ORDEM_EXECUCAO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_REGUA_EXEC ON LARA_REGUA_EXECUCOES (ETAPA, DATA_HORA_EXECUCAO)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_LARA_CFG_CHAVE ON LARA_CONFIGURACOES (CHAVE)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_INT_IDEMP ON LARA_INTEGRACOES_LOG (IDEMPOTENCY_KEY)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

DECLARE
  ex_obj_exists EXCEPTION;
  ex_index_col_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_obj_exists, -955);
  PRAGMA EXCEPTION_INIT(ex_index_col_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LARA_INT_CREATED ON LARA_INTEGRACOES_LOG (CREATED_AT)';
EXCEPTION
  WHEN ex_obj_exists OR ex_index_col_exists THEN NULL;
END;
/

MERGE INTO LARA_CONFIGURACOES tgt
USING (
  SELECT 'JANELA_CONTEXTO_HORAS' CHAVE, '72' VALOR, 'Janela para reaproveitar contexto de regua ativa.' DESCRICAO FROM DUAL
  UNION ALL
  SELECT 'JANELA_RESPOSTA_SEM_IDENTIFICACAO_MIN', '120', 'Janela para nao pedir identificacao novamente.' FROM DUAL
  UNION ALL
  SELECT 'RATE_LIMIT_WEBHOOK_POR_MIN', '60', 'Limite de requisicoes por minuto para webhooks.' FROM DUAL
  UNION ALL
  SELECT 'LARA_BASE_BOLETO_URL', 'https://pagamentos.exemplo.local/boleto', 'URL base para boleto.' FROM DUAL
  UNION ALL
  SELECT 'LARA_PIX_CHAVE', 'financeiro@empresa.com.br', 'Chave PIX padrao.' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_ATIVO', 'false', 'Ativa a sincronizacao diaria dos titulos em aberto.' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_HORA', '6', 'Hora da sincronizacao diaria (0-23).' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_MINUTO', '0', 'Minuto da sincronizacao diaria (0-59).' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_TIMEZONE', 'America/Sao_Paulo', 'Fuso horario da sincronizacao diaria.' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_LIMIT', '30000', 'Limite maximo de titulos na carga diaria.' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_DAILY_INCLUDE_DESD', 'false', 'Inclui codcob DESD na carga diaria.' FROM DUAL
  UNION ALL
  SELECT 'LARA_SYNC_STARTUP_RUN', 'true', 'Executa sincronizacao ao subir o backend.' FROM DUAL
) src
ON (tgt.CHAVE = src.CHAVE)
WHEN MATCHED THEN UPDATE SET
  tgt.VALOR = src.VALOR,
  tgt.DESCRICAO = src.DESCRICAO,
  tgt.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, CHAVE, VALOR, DESCRICAO, UPDATED_AT)
  VALUES (RAWTOHEX(SYS_GUID()), src.CHAVE, src.VALOR, src.DESCRICAO, SYSTIMESTAMP);

MERGE INTO LARA_REGUA_TEMPLATES tgt
USING (
  SELECT 'D-3' ETAPA, 'Preventivo D-3' NOME_TEMPLATE, 'WHATSAPP' CANAL, 'Ola {cliente}, lembramos que o titulo {duplicata} vence em {vencimento}. Deseja boleto ou PIX?' MSG, 1 ORDEM FROM DUAL
  UNION ALL
  SELECT 'D0', 'Vencimento D0', 'WHATSAPP', 'Ola {cliente}, o titulo {duplicata} vence hoje no valor de {valor}. Posso enviar o pagamento?', 2 FROM DUAL
  UNION ALL
  SELECT 'D+3', 'Cobranca D+3', 'WHATSAPP', 'Ola {cliente}, identificamos titulo vencido ha 3 dias. Posso enviar boleto ou PIX?', 3 FROM DUAL
  UNION ALL
  SELECT 'D+7', 'Cobranca D+7', 'WHATSAPP', 'Ola {cliente}, ainda consta pendencia em aberto. Quer receber o pagamento agora?', 4 FROM DUAL
  UNION ALL
  SELECT 'D+15', 'Cobranca D+15', 'WHATSAPP', 'Ola {cliente}, temos titulos em atraso e precisamos da regularizacao. Posso enviar as opcoes de pagamento?', 5 FROM DUAL
  UNION ALL
  SELECT 'D+30', 'Cobranca D+30', 'WHATSAPP', 'Ola {cliente}, a pendencia segue em aberto ha mais de 30 dias. Podemos tratar com prioridade?', 6 FROM DUAL
) src
ON (tgt.ETAPA = src.ETAPA AND tgt.ORDEM_EXECUCAO = src.ORDEM)
WHEN MATCHED THEN UPDATE SET
  tgt.NOME_TEMPLATE = src.NOME_TEMPLATE,
  tgt.CANAL = src.CANAL,
  tgt.MENSAGEM_TEMPLATE = src.MSG,
  tgt.ATIVO = 1,
  tgt.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, ETAPA, NOME_TEMPLATE, CANAL, MENSAGEM_TEMPLATE, ATIVO, ORDEM_EXECUCAO, CREATED_AT, UPDATED_AT)
  VALUES (RAWTOHEX(SYS_GUID()), src.ETAPA, src.NOME_TEMPLATE, src.CANAL, src.MSG, 1, src.ORDEM, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
