-- RECONAI / Torre de Controle
-- Base Oracle WinThor para Recebiveis de Cartao
-- Tabelas-fonte: PCCOB, PCPEDC, PCPEDI, PCFILIAL, PCPLPAG

--------------------------------------------------------------------------------
-- 1) View base de vendas faturadas (cabecalho + itens)
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_VENDAS_CARTAO_FATURADAS AS
SELECT
  P.CODFILIAL,
  F.RAZAOSOCIAL AS NOME_FILIAL,
  P.NUMPED,
  NVL(P.DTFAT, P.DATA) AS DATA_VENDA,
  P.CODCLI,
  P.CODCOB,
  COB.COBRANCA AS DESCRICAO_COBRANCA,
  P.CODPLPAG,
  PL.DESCRICAO AS DESCRICAO_PLPAG,
  P.VLTOTAL AS VALOR_PEDIDO,
  IT.VALOR_ITENS_FATURADOS AS VALOR_ITENS,
  P.POSICAO AS POSICAO_CABECALHO,
  IT.POSICAO_ITEM_FATURADO AS POSICAO_ITEM,
  CASE
    WHEN ABS(NVL(P.VLTOTAL, 0) - NVL(IT.VALOR_ITENS_FATURADOS, 0)) > 0.01 THEN 1
    ELSE 0
  END AS IND_DIVERGENCIA_VALOR
FROM PCPEDC P
LEFT JOIN (
  SELECT
    I.NUMPED,
    SUM(CASE WHEN I.POSICAO = 'F' THEN NVL(I.QT, 0) * NVL(I.PVENDA, 0) ELSE 0 END) AS VALOR_ITENS_FATURADOS,
    SUM(CASE WHEN I.POSICAO = 'F' THEN 1 ELSE 0 END) AS ITENS_FATURADOS,
    MAX(CASE WHEN I.POSICAO = 'F' THEN 'F' ELSE NULL END) AS POSICAO_ITEM_FATURADO
  FROM PCPEDI I
  GROUP BY I.NUMPED
) IT ON IT.NUMPED = P.NUMPED
LEFT JOIN PCCOB COB ON COB.CODCOB = P.CODCOB
LEFT JOIN PCFILIAL F ON F.CODIGO = P.CODFILIAL
LEFT JOIN PCPLPAG PL ON PL.CODPLPAG = P.CODPLPAG
WHERE P.POSICAO = 'F';

--------------------------------------------------------------------------------
-- 2) Base de vendas faturadas com filtro de configuracao de cartao
--------------------------------------------------------------------------------
SELECT
  V.*
FROM VW_VENDAS_CARTAO_FATURADAS V
JOIN RC_CFG_COBRANCA_CARTAO CFG
  ON CFG.CODCOB = V.CODCOB
 AND CFG.ATIVO = 1
WHERE V.DATA_VENDA BETWEEN :DATA_INICIO AND :DATA_FIM;

--------------------------------------------------------------------------------
-- 3) Inconsistencias
--------------------------------------------------------------------------------

-- 3.1) Pedido faturado cartao sem agenda prevista
SELECT
  V.CODFILIAL,
  V.NOME_FILIAL,
  V.NUMPED,
  V.DATA_VENDA,
  V.CODCOB,
  V.DESCRICAO_COBRANCA,
  V.CODPLPAG,
  V.DESCRICAO_PLPAG,
  V.VALOR_PEDIDO
FROM VW_VENDAS_CARTAO_FATURADAS V
JOIN RC_CFG_COBRANCA_CARTAO CFG
  ON CFG.CODCOB = V.CODCOB
 AND CFG.ATIVO = 1
LEFT JOIN (
  SELECT DISTINCT NUMPED, CODFILIAL, CODCOB
  FROM RC_RECEBIVEL_CARTAO_PREV
) R
  ON R.NUMPED = V.NUMPED
 AND R.CODFILIAL = V.CODFILIAL
 AND R.CODCOB = V.CODCOB
WHERE V.DATA_VENDA BETWEEN :DATA_INICIO AND :DATA_FIM
  AND R.NUMPED IS NULL;

-- 3.2) Pedido nao faturado incluído indevidamente na agenda
SELECT
  R.CODFILIAL,
  R.NUMPED,
  R.CODCOB,
  R.PARCELA,
  P.POSICAO AS POSICAO_CABECALHO
FROM RC_RECEBIVEL_CARTAO_PREV R
LEFT JOIN PCPEDC P ON P.NUMPED = R.NUMPED
WHERE P.POSICAO IS NULL OR P.POSICAO <> 'F';

-- 3.3) Divergencia cabecalho x itens
SELECT
  P.CODFILIAL,
  P.NUMPED,
  P.CODCOB,
  P.VLTOTAL AS VALOR_CABECALHO,
  IT.VALOR_ITENS
FROM PCPEDC P
JOIN (
  SELECT
    I.NUMPED,
    SUM(CASE WHEN I.POSICAO = 'F' THEN NVL(I.QT, 0) * NVL(I.PVENDA, 0) ELSE 0 END) AS VALOR_ITENS
  FROM PCPEDI I
  GROUP BY I.NUMPED
) IT ON IT.NUMPED = P.NUMPED
WHERE NVL(P.DTFAT, P.DATA) BETWEEN :DATA_INICIO AND :DATA_FIM
  AND P.POSICAO = 'F'
  AND ABS(NVL(P.VLTOTAL, 0) - NVL(IT.VALOR_ITENS, 0)) > 0.01;

-- 3.4) CODCOB de cartao usado na venda, mas sem configuracao ativa
SELECT
  P.CODCOB,
  COB.COBRANCA,
  COUNT(*) AS QUANTIDADE_VENDAS
FROM PCPEDC P
LEFT JOIN PCCOB COB ON COB.CODCOB = P.CODCOB
WHERE NVL(P.DTFAT, P.DATA) BETWEEN :DATA_INICIO AND :DATA_FIM
  AND P.POSICAO = 'F'
  AND NVL(COB.CARTAO, 'N') = 'S'
  AND NOT EXISTS (
    SELECT 1
    FROM RC_CFG_COBRANCA_CARTAO CFG
    WHERE CFG.CODCOB = P.CODCOB
      AND CFG.ATIVO = 1
  )
GROUP BY P.CODCOB, COB.COBRANCA
ORDER BY COUNT(*) DESC;

-- 3.5) Plano usado em venda de cartao sem regra ativa
SELECT
  P.CODPLPAG,
  PL.DESCRICAO AS DESCRICAO_PLPAG,
  COUNT(*) AS QUANTIDADE_VENDAS
FROM PCPEDC P
LEFT JOIN PCPLPAG PL ON PL.CODPLPAG = P.CODPLPAG
WHERE NVL(P.DTFAT, P.DATA) BETWEEN :DATA_INICIO AND :DATA_FIM
  AND P.POSICAO = 'F'
  AND EXISTS (
    SELECT 1
    FROM RC_CFG_COBRANCA_CARTAO CFG
    WHERE CFG.CODCOB = P.CODCOB
      AND CFG.ATIVO = 1
  )
  AND NOT EXISTS (
    SELECT 1
    FROM RC_CFG_PLPAG_CARTAO PC
    WHERE PC.CODPLPAG = P.CODPLPAG
      AND PC.ATIVO = 1
  )
GROUP BY P.CODPLPAG, PL.DESCRICAO
ORDER BY COUNT(*) DESC;

